goat/urls.py
from django.conf.urls import patterns, url

from .views import WordListView, WordDetailView,\
                   DictView, CategoryView

urlpatterns = patterns('',
    url(r'^$', WordListView.as_view(), name='index'),
    url(r'^word/(?P<pk>\d+)/(?P<slug>[-\w]+)/$', WordDetailView.as_view(), name='word-detail'),
    url(r'^dict/(?P<pre>[#%0-9a-z]+)/$', DictView.as_view(), name='dict'),
    url(r'^cat/(?P<pk>\d+)/(?P<slug>[-\w]+)/$', CategoryView.as_view(), name='cat'),
)

sura/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'sura.views.home', name='home'),
    # url(r'^sura/', include('sura.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('goat.urls', namespace='goat')),
)

goat/models.py
from django.db import models
from djorm_pgarray.fields import ArrayField
from djorm_expressions.models import ExpressionManager
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify

from .utils import first_words


# Ref: http://www.craigkerstiens.com/2012/11/06/django-and-arrays/

class SlugMixIn:
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        return super().save(*args, **kwargs)


class Word(models.Model):
    text = models.CharField(max_length=160)
    slug = models.CharField(max_length=160)
    definition = models.TextField()
    pub_date = models.DateField('Published on', null=True, blank=True)
    tags = ArrayField(dbtype='varchar(160)', null=True, blank=True)
    author = models.ForeignKey(User, null=True, blank=True)
    category = models.ForeignKey('Category', null=True, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    published = models.BooleanField(default=False)
    objects = ExpressionManager()


    def __str__(self):
        return self.text


    def save(self, *args, **kwargs):
        self.slug = slugify(self.text)
        return super().save(*args, **kwargs)


class Example(models.Model):
    text = models.TextField()
    word = models.ForeignKey(Word)

    def __str__(self):
        return '{}:{}'.format(self.word.text, first_words(self.text, 3))


class Category(SlugMixIn, models.Model):
    name = models.CharField(max_length=160)
    slug = models.CharField(max_length=160)
    created_date = models.DateTimeField(auto_now_add=True)
    published = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

goat/forms.py
from django import forms
from .models import Word, Category

# This field is to used with djorm_pgarray's ArrayField
class TagsArrayField(forms.CharField):
    def to_python(self, value):
        text = super(TagsArrayField, self).to_python(value)
        # text is the string we get from TextInput widget.
        # Wrap with {} to comply with PostgreSQL syntax to
        # store to database
        return '{{{0}}}'.format(text)

    def prepare_value(self, value):
        # value is list of string,
        # we join them with commas
        # to show on TextInput widget
        commajoined = ', '.join(value) if value else value
        return super(TagsArrayField, self).prepare_value(commajoined)



class WordForm(forms.ModelForm):
    tags = TagsArrayField()

    class Meta:
        model = Word
        exclude = ('pub_date', 'slug')


class CategoryForm(forms.ModelForm):
    class Meta():
        model = Category
        exclude = ('pub_date', 'slug')

goat/views.py
# Create your views here.
from django.conf.urls import patterns, url
from django.views.generic import ListView, DetailView
from .models import Word, Category


class WordListView(ListView):
    model = Word

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(published=True)



class WordDetailView(DetailView):
    model = Word



class DictView(WordListView):
    def get_queryset(self):
        queryset = super().get_queryset()
        prefix = self.kwargs['pre']
        # Prefix is 'a' to 'z'
        if prefix.isalpha():
            return queryset.filter(text__istartswith=prefix)
        # Prefix is '#'
        for i in range(ord('a'), ord('z')):
            queryset = queryset.exclude(text__istartswith=chr(i))
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['dict'] = self.kwargs['pre']
        return context



class CategoryView(WordListView):
    def get_queryset(self):
        queryset = super().get_queryset()
        cat = Category.objects.get(pk=self.kwargs['pk'])
        return queryset.filter(category=cat)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cat'] = self.kwargs['pk']
        return context

goat/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  <meta name='viewport' content="width=device-width, initial-scale=1.0">
  <meta name='description' content="">
  <meta name='author' content="">
  <!-- Bootstrap -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel='stylesheet' media='screen'>
  <link href="{% static 'css/site.css' %}" rel='stylesheet'>
  <script src="{% static 'js/jquery.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  {% block extracss %}{% endblock %}
  {% block extrajs %}{% endblock %}
</head>
<body>

  <div class='navbar navbar-inverse navbar-fixed-top'>
    <div class='navbar-inner'>
      <div class='container'>
        <button type='button' class='btn btn-navbar' data-toggle='collapse' data-target=".nav-collapse">
          <span class='icon-bar'></span>
          <span class='icon-bar'></span>
          <span class='icon-bar'></span>
        </button>
        <a class='brand' href='/'>Sura Dict</a>
        <div class='nav-collapse collapse'>
          <ul class='nav'>
            <li class='active'><a href='/'>Home</a></li>
            <li><a href="/about">About</a></li>
            <li><a href="/contact">Contact</a></li>
            <li class='dropdown'>
              <a href='#' class='dropdown-toggle' data-toggle='dropdown'>Dropdown <b class='caret'></b></a>
              <ul class='dropdown-menu'>
                <li><a href='#'>Action</a></li>
                <li><a href='#'>Another action</a></li>
                <li><a href='#'>Something else here</a></li>
                <li class='divider'></li>
                <li class='nav-header'>Nav header</li>
                <li><a href='#'>Separated link</a></li>
                <li><a href='#'>One more separated link</a></li>
              </ul>
            </li>
          </ul>
          <form class='navbar-form pull-right'>
            <input class='span2' type='text' placeholder='Email'>
            <input class='span2' type='password' placeholder='Password'>
            <button type='submit' class='btn'>Sign in</button>
          </form>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>

  {% include 'goat/categorylinks.html' %}

  <div class='container'>
    <div class='span8'>
      {% block content %}
      {% endblock %}
    </div>
    <div class='span3'></div>
  </div>

  <div class='container'>
    <footer>
      <p>&copy; Sura 2013</p>
    </footer>
  </div> <!-- /container -->
</body>
</html>

goat/templates/goat/categorylinks.html
{% load staticfiles %}
{% load url from future %}

{% load goat_filters %}

<div class='container categorylinks'>
  <div class='tabbable'>
    <ul class='nav nav-tabs' id='categorytabs'>
      <li class="{% if not cat %}active{% endif %}">
        <a href='#tab1' data-toggle='tab'>Dictionary</a>
      </li>
      <li class="{{cat|yesno:'active,'}}">
        <a href='#tab2' data-toggle='tab'>Categories</a>
      </li>
    </ul>
    <div class='tab-content'>
      <div class="tab-pane pagination {% if not cat %}active{% endif %}" id='tab1'>
        <ul>
        {% for a in alphabet %}
          <li class="{{ dict|active_if_equal:a }}">
            <a href="{% url 'goat:dict' a %}">{{ a|unquote|upper }}</a>
          </li>
        {% endfor %}
        </ul>
      </div>
      <div class="tab-pane pagination {{cat|yesno:'active,'}}" id='tab2'>
        <ul class='inline'>
        {% for pk, name, slug in categories %}
          <li class="{{ cat|active_if_equal:pk }}">
            <a href="{% url 'goat:cat' pk slug %}">{{ name }}</a>
          </li>
        {% endfor %}
        </ul>
      </div>
    </div>
  </div>
</div>

goat/templates/goat/dict.html
{% extends 'base.html' %}
{% load url from future %}

{% block title %}Sura{% endblock %}

{% block content %}

{% if word_list %}
<dl>
{% for w in word_list %}
  <dt><a href='{% url 'goat:word-detail' w.pk w.slug %}'>{{ w.text }}</a></dt>
  <dd>{{ w.definition }}</dd>
{% endfor %}
</dl>
{% endif %}

{% endblock %}

goat/templates/goat/word_detail.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block title %}Sura{% endblock %}

{% block content %}

<dl>
  <dt>{{ word.text }}</dt>
  <dd>{{ word.definition }}</dd>
  <div>{% trans 'Examples' %}</div>
  <ul>
    {% for ex in word.example_set.all %}
      <li>
        {{ ex.text }}
      </li>
    {% endfor %}
  </ul>

</dl>

{% endblock content %}

goat/templates/goat/word_list.html
{% extends 'base.html' %}
{% load url from future %}

{% block title %}Sura{% endblock %}

{% block content %}

{% if word_list %}
<dl>
{% for w in word_list %}
  <dt><a href='{% url 'goat:word-detail' w.pk w.slug %}'>{{ w.text }}</a></dt>
  <dd>{{ w.definition }}</dd>
{% endfor %}
</dl>
{% endif %}

{% endblock %}

goat/templates/hero.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Bootstrap, from Twitter</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="../assets/css/bootstrap.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
    </style>
    <link href="../assets/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="../assets/ico/favicon.png">
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="#">Project name</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Action</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li class="divider"></li>
                  <li class="nav-header">Nav header</li>
                  <li><a href="#">Separated link</a></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li>
            </ul>
            <form class="navbar-form pull-right">
              <input class="span2" type="text" placeholder="Email">
              <input class="span2" type="password" placeholder="Password">
              <button type="submit" class="btn">Sign in</button>
            </form>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">

      <!-- Main hero unit for a primary marketing message or call to action -->
      <div class="hero-unit">
        <h1>Hello, world!</h1>
        <p>This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        <p><a href="#" class="btn btn-primary btn-large">Learn more &raquo;</a></p>
      </div>

      <!-- Example row of columns -->
      <div class="row">
        <div class="span4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn" href="#">View details &raquo;</a></p>
        </div>
        <div class="span4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn" href="#">View details &raquo;</a></p>
       </div>
        <div class="span4">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn" href="#">View details &raquo;</a></p>
        </div>
      </div>

      <hr>

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="../assets/js/jquery.js"></script>
    <script src="../assets/js/bootstrap-transition.js"></script>
    <script src="../assets/js/bootstrap-alert.js"></script>
    <script src="../assets/js/bootstrap-modal.js"></script>
    <script src="../assets/js/bootstrap-dropdown.js"></script>
    <script src="../assets/js/bootstrap-scrollspy.js"></script>
    <script src="../assets/js/bootstrap-tab.js"></script>
    <script src="../assets/js/bootstrap-tooltip.js"></script>
    <script src="../assets/js/bootstrap-popover.js"></script>
    <script src="../assets/js/bootstrap-button.js"></script>
    <script src="../assets/js/bootstrap-collapse.js"></script>
    <script src="../assets/js/bootstrap-carousel.js"></script>
    <script src="../assets/js/bootstrap-typeahead.js"></script>

  </body>
</html>